config/routes.rb
FashionHackathon13::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'

  resources :users
  resources :styles

  post 'search_fields', to: 'home#search_fields'
end

app/models/style.rb
# == Schema Information
#
# Table name: styles
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#  title              :string(255)
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  size               :string(255)
#  brand              :string(255)
#  color              :string(255)
#

class Style < ActiveRecord::Base
  attr_accessible :user_id, :image, :title, :size, :brand, :color
  belongs_to :user
  has_attached_file :image, :styles => { :main => '500x500>', :thumb => '200x200>' }

  def compare_height(input_height)
    ((input_height - self.user.height) / input_height).abs
  end

  def compare_weight(input_weight)
    ((input_weight - self.user.weight) / input_weight).abs
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  height                 :integer
#  weight                 :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :height, :weight

  has_many :styles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@styles = Style.all
  end

  def search_fields
    @height = params[:height]
    @weight = params[:weight]
    @styles = Style.all
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  def index
    @styles = Style.all
  end

  def new
    @style = Style.new
  end

  def create
    @style = Style.create(params[:style])
    current_user.styles << @style
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
end

app/views/home/index.html.erb
<div class="main-homepage-wrapper">
	<div class="opacity" style="display:none;"></div>
	<div class="login-view" style="display:none;">
		<div class="login-wrapper">
			<%= render partial: "users/sessions/new" %>
		</div>
		<div class="registration-wrapper">
			<%= render partial: "users/registrations/new" %>
		</div>
	</div>
	<div class="header">
		<div class="logo">
			<%= image_tag 'logo.png' %>
		</div>

		<div class="button" id="login">Login</div>
	</div>

	<div class="search-box">
		<div class="search-wrapper">
			<h1 id="search-text">Find your FashionMate and Start Shopping</h1>
			<div class="search-form">
		      <%= form_tag '/search_fields', :remote => true, :id => 'search-fields' do %>
		        <label>Weight: </label>
		        <%= text_field_tag :weight, nil, :class => 'search-main-input', :id => 'weight', :placeholder => 'Weight' %>
		        <label>Height: </label>
		        <%= text_field_tag :height, nil, :class => 'search-main-input', :id => 'height', :placeholder => 'Height' %>
		        <%= submit_tag nil, :id => 'search', :value => 'Search' %>
		      <% end %>
		    </div>
		</div>
		<div class="search-info" style="display:none">
			<h1>These are your FashionMates!</h1>
			<h1 style="color: #300a70; font-size: 150%; margin-top: 60px;">Checkout the compatability index that tells you how similary your height and weight are to your FashionMate's</h1>
		</div>
	</div>


	<div class="content-wrapper">
		<div class="styles-wrapper-main">
			<ul class="list-wrapper">
				<%= render partial: "styles/styles" %>
			</ul>
		</div>
	</div>
</div>

app/views/home/search_fields.js.erb
$('.styles-wraper-main').empty().append("<%= render partial: "styles/styles" %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FashionHackathon13</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:100' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_image.html.erb
<li class="style-image-wrapper" data-user="">
	<div class="image-wrapper">
		<div class="main-image"><img class="style-img-thumb" src="http://cdn.reviews.rtrcdn.com/201135.jpg"></div>
	</div>
	<div class="style-metadata">
		<h1>Size Worn: 2</h1>
		<h1>Designer: Helmut Lang</h1>
	</div>
</li>

app/views/shared/image.html.erb
<li class="style-image-wrapper" data-user="<%= style.user %>">
	<div class="image-wrapper">
		<div class="main-image"><img class="style-img-thumb" src="<%= style.url %>"></div>
	</div>
	<div class="style-metadata">
		<h1>Size Worn: <%= style.sizeWorn %></h1>
		<h1>Designer: <%= style.desginer %></h1>
	</div>
</li>

app/views/styles/_styles.html.erb
<% @styles.each do |style| %>
  <li class="style-image-wrapper" data-user="">
    <h1><%= style.title %></h1>
    <div class="image-wrapper">
      <div class="main-image">
        <%= image_tag style.image.url(:main) %>
      </div>
    </div>
    <div class="style-metadata">
      <p>User: <span><%= style.user.email %> </span></p>

      <% if (@weight) %>
      <p class="comp">WeightIndex: <%= style.compute_weight(@weight) %></p>
      <% end %>

      <% if (@height) %>
      <p class="comp">HeightIndex: <%= style.compute_height(@height) %></p>
      <% end %>

      <p>Size Worn: <span><%= style.size %></span></p>
      <p>Brand: <span><%= style.brand %></span></p>
    </div>
  </li>
<% end %>

app/views/styles/index.html.erb
<% @styles.each do |style| %>
  <h1><%= style.title %></h1>
  <%= image_tag style.image.url(:main) %>
  <h1><%= style.user.email %></h1>
  <%= style.size %>
  <%= style.brand %>
  <%= style.color %>
<% end %>

app/views/styles/new.html.erb
<%= form_for @style, :url => styles_path, :html => { :multipart => true } do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :image %>
  <%= form.file_field :image %>
  <%= form.label :size %>
  <%= form.text_field :size %>
  <%= form.label :brand %>
  <%= form.text_field :brand %>
  <%= form.label :color %>
  <%= form.text_field :color %>
  <%= form.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <h1><%= user.email %></h1>
<% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= current_user.email %></h1>